Repository ultralytics/actions, pull requests merged in 2024-11, with the labels that each got.

#278 Fix PyPI downloads links
  README.md
  actions/utils/github_utils.py
Labels: documentation, enhancement

#279 Fix retry count and add docstring
  retry/action.yaml
Labels: devops

#280 Update action.yaml
  retry/action.yaml
Labels: enhancement, devops

#284 Use uv for package installation
  action.yml
Labels: dependencies, enhancement, devops

#285 Update action.yml
  action.yml
Labels: devops

#288 Slack v2 API usage
  .github/workflows/publish.yml
  action.yml
  actions/__init__.py
Labels: enhancement, devops

#290 Update action.yml
  action.yml
Labels: enhancement, devops

#291 Update __init__.py to v0.0.20
  actions/__init__.py
Labels: dependencies, enhancement

#292 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/publish.yml
Labels: enhancement, devops

#293 Update action.yml
  action.yml
Labels: documentation

#295 Update __init__.py
  actions/__init__.py
Labels: dependencies

#294 Prettier 3.4 update
  action.yml
  actions/__init__.py
Labels: documentation, enhancement, devops

#297 Add base SHA to printout
  actions/utils/github_utils.py
Labels: enhancement, devops

#298 Update to v0.0.22 with SHA report
  actions/__init__.py
Labels: dependencies, enhancement
