Repository ultralytics/actions, pull requests merged in 2024-12, with the labels that each got.

#303 Update action.yml
  action.yml
Labels: enhancement, devops

#306 Update publish.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#305 Update version check
  actions/__init__.py
  actions/utils/github_utils.py
Labels: enhancement, devops

#307 Use uv pip install
  .github/workflows/publish.yml
Labels: enhancement, devops

#308 Update publish.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#309 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, devops

#311 Update github_utils.py
  actions/utils/__init__.py
  actions/utils/github_utils.py
Labels: enhancement, devops

#315 Update action.yml
  action.yml
Labels: enhancement, devops

#317 Update action.yml
  action.yml
Labels: enhancement, devops

#318 Mark merged PR issues as 'fixed'
  action.yml
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, fixed, devops

#319 Remove TODO tags on closed PRs
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, devops

#320 Message Issue authors on Merged PRs
  action.yml
  actions/__init__.py
  actions/first_interaction.py
  actions/summarize_pr.py
Labels: enhancement, fixed, devops

#321 Use measured language on fix comments
  actions/summarize_pr.py
Labels: documentation, enhancement

#322 Inspire PR contributors on merge
  actions/__init__.py
  actions/summarize_pr.py
  actions/utils/__init__.py
  actions/utils/github_utils.py
Labels: enhancement, devops

#323 Improve comments
  actions/__init__.py
  actions/summarize_pr.py
Labels: documentation, enhancement

#324 Fix reviews and comments list merge
  actions/__init__.py
  actions/summarize_pr.py
Labels: bug, devops

#325 Use timestamp-based RNG seed
  actions/utils/openai_utils.py
Labels: enhancement, devops

#326 Do not reply to bot PRs
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, devops

#327 Credit PR authors in issue messages
  actions/summarize_pr.py
Labels: enhancement, devops

#328 Credit PR committers
  action.yml
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, devops

#329 Remove default `fetch-depth: 0`
  action.yml
Labels: enhancement, devops

#330 Remove `git pull` operation
  action.yml
Labels: enhancement, devops

#331 lycheeverse/lychee-action@v2.2.0
  action.yml
Labels: dependencies, enhancement, devops

#332 Update summarize_pr.py
  action.yml
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, devops

#334 Update first_interaction.py
  actions/first_interaction.py
Labels: documentation, devops

#335 Cleanup
  actions/utils/__init__.py
  actions/utils/github_utils.py
Labels: documentation, enhancement, devops

#337 Update pyproject.toml
  pyproject.toml
Labels: enhancement, devops

#336 Convert to classes
  .github/workflows/format.yml
  action.yml
  actions/__init__.py
  actions/first_interaction.py
  actions/summarize_pr.py
  actions/summarize_release.py
  actions/utils/__init__.py
  actions/utils/github_utils.py
Labels: enhancement, devops
