Repository ultralytics/actions, pull requests merged in 2024-10, with the labels that each got.

#241 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/tag.yml
  README.md
  utils/first_interaction.py
Labels: documentation, enhancement

#242 Remove Azure from LLM options
  action.yml
  utils/first_interaction.py
  utils/summarize_pr.py
  utils/summarize_release.py
Labels: enhancement

#243 Ultralytics-Actions Python package
  .github/workflows/publish.yml
  .github/workflows/tag.yml
  action.yml
  actions/__init__.py
  actions/first_interaction.py
  actions/summarize_pr.py
  actions/summarize_release.py
  actions/update_markdown_code_blocks.py
  actions/utils/__init__.py
  actions/utils/common_utils.py
  actions/utils/github_utils.py
  actions/utils/openai_utils.py
  pyproject.toml
Labels: enhancement

#245 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#244 Use PyPI trusted publisher
  .github/workflows/publish.yml
  README.md
  action.yml
Labels: dependencies, enhancement

#246 Remove redundant utils dir
  utils/first_interaction.py
  utils/summarize_pr.py
  utils/summarize_release.py
  utils/update_markdown_code_blocks.py
Labels: enhancement

#250 Add URL checks to responses
  action.yml
  actions/__init__.py
  actions/utils/common_utils.py
  actions/utils/openai_utils.py
Labels: enhancement

#251 New Actions Info function
  action.yml
  actions/__init__.py
  actions/utils/__init__.py
  actions/utils/github_utils.py
  pyproject.toml
Labels: enhancement

#253 Simplify Actions
  action.yml
  actions/first_interaction.py
  actions/summarize_pr.py
  actions/summarize_release.py
  actions/utils/__init__.py
  actions/utils/github_utils.py
  actions/utils/openai_utils.py
Labels: enhancement

#258 Ignore github URLs in broken link checks
  actions/utils/common_utils.py
Labels: enhancement

#259 Updated URL checks
  actions/__init__.py
  actions/utils/common_utils.py
Labels: enhancement

#260 Update common_utils.py
  actions/__init__.py
  actions/utils/common_utils.py
Labels: enhancement

#261 New Retry Action
  retry/action.yaml
Labels: enhancement

#262 Simplify PR summary update
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement

#263 Fix duplicate PR summary
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, fixed

#264 Update summarize_pr.py
  actions/__init__.py
  actions/summarize_pr.py
Labels: documentation, enhancement

#265 Print Ultralytics Actions version
  actions/__init__.py
  actions/summarize_pr.py
  actions/utils/github_utils.py
Labels: enhancement

#266 Fix duplicate PR summary
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement

#267 Disk Space Cleanup Action
  disk-space-cleanup/action.yml
Labels: enhancement, devops

#268 Rename Cleanup disk action
  cleanup-disk/action.yml
Labels: enhancement, devops

#269 Stop attempting to remove Android cache
  cleanup-disk/action.yml
Labels: devops

#270 Update retry/action.yaml
  retry/action.yaml
Labels: devops

#271 Prettier ignore npm and poetry lock files
  action.yml
  actions/__init__.py
  pyproject.toml
Labels: dependencies, devops

#272 Update publish.yml
  .github/workflows/publish.yml
Labels: devops

#273 Update action.yml
  action.yml
Labels: enhancement, devops

#274 Ignore lockfiles for spelling
  action.yml
Labels: documentation, enhancement, devops
