Repository ultralytics/actions, pull requests merged in 2024-08, with the labels that each got.

#151 Format CSS
  action.yml
Labels: enhancement

#152 Update format.yml
  .github/workflows/format.yml
  README.md
Labels: dependencies, enhancement

#153 Add swift formatting option
  action.yml
Labels: dependencies, enhancement

#155 Update README.md
  README.md
Labels: documentation, enhancement

#156 Add Alert label
  utils/autolabel_issue.py
Labels: documentation, enhancement

#157 Close and Lock Alert Issues
  utils/autolabel_issue.py
Labels: enhancement, Alert

#160 Update Alert action
  utils/autolabel_issue.py
Labels: documentation, enhancement

#161 Ignore Alerts for Org members
  utils/autolabel_issue.py
Labels: HUB, enhancement

#162 Remove mdformat
  .github/workflows/format.yml
  README.md
  action.yml
  utils/autolabel_issue.py
Labels: dependencies, documentation, enhancement

#163 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: dependencies, documentation, enhancement

#164 Git rebase before adding changes
  action.yml
Labels: dependencies, enhancement

#166 Git commit first before pull and rebase
  action.yml
Labels: enhancement

#167 Ignore PR comments for autolabel actions 2
  utils/autolabel_issue.py
Labels: enhancement

#169 Ignore F821 undefined name in code blocks
  utils/update_markdown_code_blocks.py
Labels: dependencies, enhancement

#170 Ignore F841
  utils/update_markdown_code_blocks.py
Labels: dependencies, enhancement

#171 Remove --pre-summary-newline
  action.yml
  utils/update_markdown_code_blocks.py
Labels: enhancement

#172 Reinstate --close-quotes-on-newline
  action.yml
  utils/update_markdown_code_blocks.py
Labels: documentation, enhancement

#174 Ruff docstring formatting
  action.yml
  utils/update_markdown_code_blocks.py
Labels: documentation, enhancement

#175 Fix for Google style
  action.yml
  utils/autolabel_issue.py
  utils/update_markdown_code_blocks.py
Labels: enhancement

#176 Update action.yml
  action.yml
Labels: documentation, enhancement

#177 Reduce autolabel wait to 10 seconds
  action.yml
  utils/autolabel_issue.py
Labels: documentation, enhancement

#178 Fix git pull before git commit
  action.yml
Labels: enhancement

#179 Update action.yml for Ruff --unsafe-fixes
  action.yml
Labels: enhancement

#180 Add https://www.reddit.com/r/Ultralytics/ badge
  README.md
Labels: documentation, enhancement

#181 Add Summarize Release action
  action.yml
  utils/autolabel_issue.py
  utils/summarize_pr.py
  utils/summarize_release.py
Labels: enhancement

#183 Improve Release Summary action
  utils/autolabel_issue.py
  utils/summarize_pr.py
  utils/summarize_release.py
Labels: enhancement

#184 Update summarize_release.py
  utils/summarize_release.py
Labels: enhancement
