Repository ultralytics/actions, pull requests merged in 2024-09, with the labels that each got.

#189 Update summarize_release.py
  utils/summarize_release.py
Labels: documentation, enhancement

#192 Add Ruff --extend-select UP with Python 3.8
  action.yml
Labels: enhancement

#193 Update summarize_release.py
  utils/autolabel_issue.py
  utils/summarize_release.py
  utils/update_markdown_code_blocks.py
Labels: documentation, enhancement

#195 Create tag.yml
  .github/tag.yml
Labels: dependencies, enhancement

#194 Update `summarize_release` with New Contributors section
  utils/summarize_release.py
Labels: enhancement

#196 Rename .github/tag.yml to .github/workflows/tag.yml
  .github/workflows/tag.yml
Labels: enhancement, good first issue

#197 Fix tag.yml from /docs to /actions
  .github/workflows/tag.yml
Labels: enhancement

#198 Update autolabel_issue.py to sleep 3s
  utils/autolabel_issue.py
Labels: enhancement

#200 Update summarize_release.py with PR newlines
  utils/summarize_release.py
Labels: enhancement

#204 Update action.yml
  action.yml
  utils/autolabel_issue.py
Labels: dependencies, enhancement

#205 Update autolabel_issue.py
  utils/autolabel_issue.py
Labels: enhancement

#207 New First interaction
  action.yml
  utils/first_interaction.py
Labels: enhancement

#208 Update first_interaction.py
  utils/first_interaction.py
  utils/summarize_pr.py
Labels: documentation, enhancement

#209 Update first_interaction.py
  utils/first_interaction.py
Labels: enhancement

#214 Fix empty defaults being used
  utils/first_interaction.py
Labels: enhancement

#218 Update first_interaction.py
  utils/first_interaction.py
Labels: documentation, enhancement

#219 Update first_interaction.py
  utils/first_interaction.py
Labels: documentation, enhancement

#220 Add discussions to first_interaction.py
  utils/first_interaction.py
  utils/summarize_pr.py
  utils/summarize_release.py
Labels: enhancement

#224 Update action.yml
  action.yml
Labels: dependencies, enhancement

#226 Fix GraphQL labels
  utils/first_interaction.py
Labels: enhancement

#227 Update first_interaction.py
  utils/first_interaction.py
Labels: enhancement

#231 Fix discussion labels
  utils/first_interaction.py
Labels: documentation, enhancement

#232 Simplify action type reading
  utils/first_interaction.py
Labels: enhancement

#235 Update first_interaction.py
  utils/first_interaction.py
Labels: documentation, enhancement

#236 Update summarize_release.py
  utils/summarize_release.py
Labels: enhancement

#238 Do not @ giscus bot
  utils/first_interaction.py
Labels: enhancement
