Repository ultralytics/actions, pull requests merged in 2025-05, with the labels that each got.

#433 Update format.yml
  .github/workflows/format.yml
  README.md
Labels: documentation

#434 Update format.yml
  .github/workflows/format.yml
  README.md
Labels: enhancement, devops

#435 Update README.md with CI badge
  .github/workflows/ci.yml
  README.md
Labels: documentation, enhancement

#436 Update pyproject.toml
  .github/workflows/ci.yml
  pyproject.toml
Labels: dependencies, enhancement

#437 Add CodeCov badge
  README.md
Labels: documentation, enhancement

#438 Add tests for GitHub utilities
  tests/test_cli_commands.py
  tests/test_common_utils.py
  tests/test_github_utils.py
  tests/test_init.py
  tests/test_openai_utils.py
  tests/test_update_markdown_codeblocks.py
Labels: enhancement, devops

#439 Additional tests for improved coverage
  tests/test_dispatch_actions.py
  tests/test_first_interaction.py
  tests/test_summarize_pr.py
  tests/test_summarize_release.py
Labels: enhancement, devops

#440 Add dart formatting
  README.md
  action.yml
Labels: enhancement, devops

#441 Add is_repo_public()
  .github/workflows/format.yml
  action.yml
  actions/utils/github_utils.py
Labels: enhancement, devops

#442 Fix format.yml branch
  .github/workflows/format.yml
Labels: enhancement, devops

#443 Add automated file header updates
  action.yml
  actions/__init__.py
  actions/update_file_headers.py
  pyproject.toml
Labels: enhancement, devops

#444 Fix ultralytics-actions-headers command typo
  action.yml
  actions/__init__.py
  actions/update_file_headers.py
  pyproject.toml
Labels: enhancement, devops

#445 Update shebang
  actions/__init__.py
  actions/update_file_headers.py
Labels: enhancement, devops

#446 Update update_file_headers.py
  actions/__init__.py
  actions/update_file_headers.py
  tests/test_cli_commands.py
Labels: documentation, enhancement

#447 Add Permissions to Ultralytics Actions `format.yml`
  .github/workflows/format.yml
Labels: enhancement, devops

#449 Update header checks and version
  actions/__init__.py
  actions/update_file_headers.py
Labels: enhancement, devops

#450 Add Vue and Next.js file header formats
  actions/__init__.py
  actions/update_file_headers.py
Labels: dependencies, enhancement

#451 Disable Vue due to 80-char wrap bug
  actions/__init__.py
  actions/update_file_headers.py
Labels: bug, dependencies, enhancement

#452 Update update_file_headers.py
  actions/__init__.py
  actions/update_file_headers.py
Labels: enhancement

#453 Update action.yml
  retry/action.yml
Labels: documentation

#454 Exclude autogenerated files from header action
  actions/__init__.py
  actions/update_file_headers.py
Labels: enhancement, devops

#455 Create test_headers.py
  tests/test_headers.py
Labels: enhancement, devops

#456 Update and rename test_headers.py to test_file_headers.py
  tests/test_file_headers.py
  tests/test_headers.py
Labels: documentation, enhancement

#459 Update action.yml for Dart sdk argument
  action.yml
Labels: enhancement, devops

#457 Update ci.yml with permissions
  .github/workflows/ci.yml
Labels: enhancement, devops

#460 Remove MATLAB from update_file_headers.py
  actions/__init__.py
  actions/update_file_headers.py
Labels: enhancement, devops

#461 Potential fix for code scanning alert no. 6: Workflow does not contain permissions
  .github/workflows/test-retry.yml
Labels: enhancement, devops

#462 Update Dark install to use matrix strategy
  action.yml
Labels: enhancement, devops

#464 Update action.yml for `ignore-empty-workdir: true`
  action.yml
Labels: enhancement, devops

#465 Improve handling of too-large PR diff
  actions/__init__.py
  actions/utils/github_utils.py
Labels: enhancement, devops

#470 Test Python 3.8
  .github/workflows/ci.yml
  actions/__init__.py
  actions/utils/github_utils.py
  tests/test_github_utils.py
Labels: enhancement, devops
