Repository ultralytics/actions, pull requests merged in 2025-08, with the labels that each got.

#484 Ultralytics Actions GPT-5 update
  README.md
  action.yml
  actions/__init__.py
  actions/first_interaction.py
  actions/summarize_pr.py
  actions/summarize_release.py
  actions/utils/openai_utils.py
  tests/test_urls.py
Labels: documentation, enhancement, devops

#486 Add automated SPDX SBOM generation to releases
  .github/workflows/publish.yml
  actions/__init__.py
Labels: enhancement, devops

#489 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, devops

#490 Update pyproject.toml to `requests>=2.28.1`
  actions/__init__.py
  pyproject.toml
Labels: dependencies, devops

#492 Update openai_utils.py
  actions/__init__.py
  actions/utils/openai_utils.py
Labels: documentation, enhancement

#493 Improve GPT-5 prompt
  actions/__init__.py
  actions/utils/openai_utils.py
Labels: documentation

#494 Do not redirect GitHub asset URLs
  actions/utils/common_utils.py
Labels: enhancement, devops

#491 Assign "bug" label to only issues with sufficient information
  actions/__init__.py
  actions/first_interaction.py
Labels: enhancement, devops

#497 Ultralytics Refactor https://ultralytics.com/actions
  README.md
Labels: documentation
