Repository ultralytics/actions, pull requests merged in 2025-01, with the labels that each got.

#341 Update `is_url` link checking
  actions/utils/common_utils.py
Labels: enhancement, devops

#342 Update `check_links_in_string`
  actions/utils/common_utils.py
Labels: enhancement, devops

#344 Update requests>=2.32.3
  pyproject.toml
Labels: dependencies

#345 Update format.yml
  .github/workflows/format.yml
Labels: devops

#343 Update ruff>=0.8.4
  actions/__init__.py
  pyproject.toml
Labels: dependencies

#347 Update __init__.py
  actions/__init__.py
Labels: dependencies, devops

#346 Add tests
  .github/workflows/ci.yml
  .gitignore
  actions/__init__.py
  actions/utils/common_utils.py
  pyproject.toml
  tests/test_urls.py
Labels: dependencies, enhancement, devops

#348 Update test_urls.py
  .github/workflows/ci.yml
  actions/__init__.py
  actions/utils/common_utils.py
  pyproject.toml
  tests/test_urls.py
Labels: documentation, enhancement, devops

#350 Fix `is_url()` wildcards
  actions/__init__.py
  actions/utils/common_utils.py
  tests/test_urls.py
Labels: bug, enhancement

#351 Disable cache for speed
  action.yml
Labels: enhancement, devops

#352 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/ci.yml
Labels: enhancement, devops

#353 Add more restricted labels
  actions/__init__.py
  actions/first_interaction.py
Labels: documentation, enhancement, devops

#354 Fix retry/action.yml
  .github/workflows/test-retry.yml
  retry/action.yml
Labels: enhancement, devops

#356 Update Python retry
  retry/action.yml
Labels: devops

#357 Fix bash retry action
  retry/action.yml
Labels: enhancement, devops

#360 Apply `ruff==0.9.0` formatting
  actions/first_interaction.py
  actions/utils/github_utils.py
Labels: enhancement, devops

#361 Add prettier arg `--list-different`
  action.yml
Labels: documentation, devops

#362 Update to `ruff>=0.9.1`
  actions/__init__.py
  pyproject.toml
Labels: dependencies, devops

#364 Standardize license headers in TOML/YAML files
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/publish.yml
  .github/workflows/test-retry.yml
  action.yml
  cleanup-disk/action.yml
  pyproject.toml
  retry/action.yml
Labels: documentation

#367 Update summarize_release.py for initial releases
  actions/__init__.py
  actions/summarize_release.py
Labels: enhancement, devops

#368 Always retrieve previous tag via API
  actions/__init__.py
  actions/summarize_release.py
Labels: enhancement, devops

#369 Update summarize_release.py
  actions/__init__.py
  actions/summarize_release.py
Labels: enhancement, devops

#371 Fix MRE
  actions/first_interaction.py
Labels: documentation, enhancement

#372 `v0.0.44` Improved URL check robustness
  actions/__init__.py
  actions/utils/common_utils.py
  tests/test_urls.py
Labels: enhancement, devops

#373 Update URLs to redirects
  actions/first_interaction.py
  tests/test_urls.py
Labels: documentation

#374 `v0.0.45` requests `HEADERS` constant
  actions/__init__.py
  actions/utils/__init__.py
  actions/utils/common_utils.py
  tests/test_urls.py
Labels: enhancement, devops

#376 New URL_IGNORE_LIST
  actions/utils/common_utils.py
Labels: enhancement, devops

#377 Update action.yml
  action.yml
Labels: enhancement, devops

#378 Ignore URLs for spelling
  action.yml
Labels: enhancement, devops

#379 Ignore Carmel spelling
  action.yml
Labels: enhancement, devops

#380 Fix parenthesis in broken link checks
  actions/__init__.py
  actions/utils/common_utils.py
  tests/test_urls.py
Labels: enhancement, devops

#381 Revert URL parenthesis fix
  actions/__init__.py
  actions/utils/common_utils.py
  tests/test_urls.py
Labels: documentation

#382 Add 403 and 410 http error codes
  actions/__init__.py
  actions/utils/common_utils.py
Labels: enhancement

#383 Disable uv cache
  .github/workflows/ci.yml
Labels: devops

#384 Update action.yml
  action.yml
Labels: devops

#385 Update summarize_pr.py
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, devops

#386 Update summarize_pr.py
  actions/summarize_pr.py
Labels: enhancement, devops
