Repository ultralytics/actions, pull requests merged in 2025-03, with the labels that each got.

#389 Reduce `temperature=0.2` for summaries and labels
  actions/__init__.py
  actions/first_interaction.py
  actions/summarize_pr.py
  actions/summarize_release.py
  actions/utils/openai_utils.py
Labels: enhancement, devops

#390 Update update_markdown_code_blocks.py
  actions/__init__.py
  actions/update_markdown_code_blocks.py
Labels: documentation, devops

#391 Ignore URLs with Python fstrings
  actions/__init__.py
  actions/utils/common_utils.py
Labels: enhancement, devops

#394 Include new release version in PR merge comment
  actions/__init__.py
  actions/summarize_pr.py
Labels: enhancement, devops

#395 Format bash code blocks
  action.yml
  actions/__init__.py
  actions/update_markdown_code_blocks.py
Labels: enhancement, devops

#397 Update cleanup-disk action to remove swap space
  cleanup-disk/action.yml
Labels: enhancement, devops

#398 Ultralytics Refactor https://ultralytics.com/actions
  README.md
  tests/test_urls.py
Labels: documentation, enhancement

#400 Add Brave search API
  .github/workflows/format.yml
  action.yml
  actions/__init__.py
  actions/utils/common_utils.py
Labels: enhancement, devops
